services:
  postgres:
    image: postgres:16-alpine
    container_name: nestidp-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: nestidp
      POSTGRES_PASSWORD: nestidp
      POSTGRES_DB: nestidp
    volumes:
      - nestidp_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U nestidp -d nestidp']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  nestidp_pg_data:
