import { SamlController } from './saml.controller';

describe('SamlController', () => {
	const controller = new SamlController();

	describe('getMetadata', () => {
		it('returns not_implemented stub with correct endpoint', () => {
			expect(controller.getMetadata()).toEqual({
				status: 'not_implemented',
				endpoint: '/saml/metadata',
				message: 'IdP metadata will be generated by SamlMetadataService in a later prompt.',
			});
		});
	});

	describe('getSso', () => {
		it('returns not_implemented stub for HTTP-Redirect binding', () => {
			const result = controller.getSso();
			expect(result.status).toBe('not_implemented');
			expect(result.endpoint).toBe('/saml/sso');
			expect(result.message).toMatch(/HTTP-Redirect/i);
		});
	});

	describe('postSso', () => {
		it('returns not_implemented stub for HTTP-POST binding', () => {
			const result = controller.postSso();
			expect(result.status).toBe('not_implemented');
			expect(result.endpoint).toBe('/saml/sso');
			expect(result.message).toMatch(/HTTP-POST/i);
		});

		it('uses same endpoint path as GET sso but different binding message', () => {
			const getResult = controller.getSso();
			const postResult = controller.postSso();
			expect(getResult.endpoint).toBe(postResult.endpoint);
			expect(getResult.message).not.toBe(postResult.message);
		});
	});
});
