import { Controller, Get, HttpCode, Post } from '@nestjs/common';

@Controller('saml')
export class SamlController {
	@Get('metadata')
	@HttpCode(501)
	getMetadata() {
		return {
			status: 'not_implemented',
			endpoint: '/saml/metadata',
			message: 'IdP metadata will be generated by SamlMetadataService in a later prompt.',
		};
	}

	@Get('sso')
	@HttpCode(501)
	getSso() {
		return {
			status: 'not_implemented',
			endpoint: '/saml/sso',
			message: 'SP-initiated SSO (HTTP-Redirect) will be implemented in a later prompt.',
		};
	}

	@Post('sso')
	@HttpCode(501)
	postSso() {
		return {
			status: 'not_implemented',
			endpoint: '/saml/sso',
			message: 'SP-initiated SSO (HTTP-POST binding in) will be implemented in a later prompt.',
		};
	}
}
