-- CreateTable
CREATE TABLE "ExternalIdentityDatabase" (
    "id" TEXT NOT NULL PRIMARY KEY DEFAULT 'default',
    "dialect" TEXT NOT NULL,
    "host" TEXT NOT NULL,
    "port" INTEGER NOT NULL,
    "database" TEXT NOT NULL,
    "username" TEXT NOT NULL,
    "passwordEncrypted" TEXT NOT NULL,
    "sslMode" TEXT NOT NULL DEFAULT 'require',
    "sslCaCertPem" TEXT,
    "schemaPrefix" TEXT NOT NULL DEFAULT 'nestidp_',
    "pgSchema" TEXT,
    "keepLocalCopy" BOOLEAN NOT NULL DEFAULT false,
    "mode" TEXT NOT NULL DEFAULT 'relocate',
    "status" TEXT NOT NULL DEFAULT 'disconnected',
    "schemaVersion" INTEGER NOT NULL DEFAULT 0,
    "outOfSync" BOOLEAN NOT NULL DEFAULT false,
    "reachable" BOOLEAN NOT NULL DEFAULT false,
    "poolMax" INTEGER NOT NULL DEFAULT 10,
    "connectTimeoutMs" INTEGER NOT NULL DEFAULT 5000,
    "queryTimeoutMs" INTEGER NOT NULL DEFAULT 10000,
    "probeIntervalMs" INTEGER NOT NULL DEFAULT 20000,
    "migrationPhase" TEXT,
    "migrationDone" INTEGER NOT NULL DEFAULT 0,
    "migrationTotal" INTEGER NOT NULL DEFAULT 0,
    "lastSyncAt" DATETIME,
    "lastError" TEXT,
    "lastProbeAt" DATETIME,
    "lastProbeError" TEXT,
    "connectedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
